# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03f3c70eda02bfa61ae5f1756ed7aec722c51183b074adb5fe67151526e0aeb06e90e146440313baaafb2a68429971970f427ece4148861347749a220a1cd4c0

test:
  secret_key_base: 2f073f031afe35935d80845a14f8b701879c46bda37f5455b15726727b65dc5acaf500bc8c536a20cb3def48877de4c5680ad6ab9d0a270a02f94e5b48e6c6e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
